sudo: false
language: go

os:
- linux

env:
- ARCH=x86_64
- ARCH=i686

go:
- 1.7.4
- 1.8.x
- 1.9.x
- tip

matrix:
  fast_finish: true
  allow_failures:
  - go: tip

script:
- diff -au <(gofmt -d .) <(printf "")
- make
