sudo: false
language: go

# this ensures PRs based on a local branch are not built twice
# the downside is that a PR targeting a different branch is not built
# but as a workaround you can add the branch to this list
branches:
  only:
    - master

os:
- linux

env:
- ARCH=x86_64

go:
- 1.12.x
- tip

matrix:
  fast_finish: true
  allow_failures:
  - go: tip

addons:
  apt:
    packages:
      - devscripts

script:
- export GO111MODULE=on
- diff -au <(gofmt -d .) <(printf "")
- (cd minio && diff -au <(licensecheck --check '.go$' --recursive --lines 0 * | grep -v -w 'Apache (v2.0)') <(printf ""));
- (cd pkg && diff -au <(licensecheck --check '.go$' --recursive --lines 0 * | grep -v -w 'Apache (v2.0)') <(printf ""));
- (cd examples && diff -au <(licensecheck --check '.go$' --recursive --lines 0 * | grep -v -w 'Apache (v2.0)') <(printf ""));
- (cd docs && diff -au <(licensecheck --check '.go$' --recursive --lines 0 * | grep -v -w 'Apache (v2.0)') <(printf ""));
- make
