name: Build (Linux)

on:
  pull_request:
    branches:
    - master

permissions:
  contents: read

# This ensures that previous jobs for the PR are canceled when the PR is
# updated.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Test on Go ${{ matrix.go-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.22.x, 1.23.x]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go ${{ matrix.go-version }} on ${{ matrix.os }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Build on ${{ matrix.os }}
        env:
          MINT_MODE: full
          SERVER_ENDPOINT: localhost:9000
          ACCESS_KEY: minioadmin
          SECRET_KEY: minioadmin
          ENABLE_HTTPS: 1
          MINIO_KMS_MASTER_KEY: my-minio-key:6368616e676520746869732070617373776f726420746f206120736563726574
          MINIO_LICENSE: ${{ secrets.MINIO_LICENSE }}
          SSL_CERT_FILE: /tmp/certs-dir/public.crt
          MINIO_CI_CD: true
        run: |
          sudo apt update -y
          sudo apt install devscripts -y
          wget -O /tmp/minio https://dl.minio.io/aistor/minio/release/linux-amd64/minio
          chmod +x /tmp/minio
          mkdir -p /tmp/certs-dir
          cp testcerts/* /tmp/certs-dir
          /tmp/minio server -S /tmp/certs-dir /tmp/fs{1...4} &
          make
